version: '2'
services:
  database:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server -a demo-policy
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
    depends_on: [ database ]
    ports:
      - "8080:80"

  client:
    image: conjurinc/cli5
    depends_on: [ conjur ]
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: demo-policy
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin

    volumes:
      - ./policy:/src/policy

  conjur-tls:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    entrypoint: nginx-debug -g 'daemon off;'
    environment:
        TERM: xterm
    ports:
      - "8443:443"
    depends_on:
      - conjur
      - client
