version: '2'
services:
  database:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server -a demo-policy
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
    depends_on: [ database ]
    ports:
      - "8080:80"

  client:
    image: conjurinc/cli5
    depends_on:
      - conjur
      - proxy
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: demo-policy
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin

    volumes:
      - ./policy:/src/policy

  proxy:
    image: nginx:1.13.6-alpine
    ports:
      - "8443:443"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tls/nginx.key:/etc/nginx/nginx.key:ro
      - ./tls/nginx.crt:/etc/nginx/nginx.crt:ro
    depends_on: [ conjur ]

  ansible-python3.6:
    image: python:3.6
    volumes:
      - ../ansible:/src/ansible
    depends_on:
      - conjur
      - proxy
